name: save news

# on:
#   # push:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron: "*/5 * * * *"

on:
  repository_dispatch:
    types: [run]
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: excute python
        run: chmod +x ./news/scripts/*.py && for f in ./news/scripts/*.py ; do [ -x "$f" ] && [ ! -d "$f" ] && echo $f && python3 $f ; done
      - name: excute shell
        run: chmod +x ./news/scripts/*.sh && for f in ./news/scripts/*.sh ; do [ -x "$f" ] && [ ! -d "$f" ] && echo $f && "$f" ; done
      - name: after excute
        run: chmod +x ./news/*.py && for f in ./news/*.py ; do [ -x "$f" ] && [ ! -d "$f" ] && echo $f && python3 $f ; done
      - name: config git
        run: git config --global user.email "hemengzhi88@gmail.com"&&git config --global user.name "genkin-he"
      - name: submit
        run: git add . && git commit -m "save post" && git push origin main
        